### ISSUE TITLE
Won't continue where I am

### ISSUE THREAD

**Issue by Moortu** [nanihadesuka/NovelDokusha#101]
Sometimes the app knows where I am with a novel, but will continue from an earlier chapter.

Just today I read up to 290 and it resumed at 160.
It even says that 290 was the last read.
Furthermore, when I explicitly click on chapter 290 it still goes to chapter 160, clicking on a chapter should open the chapter.

Novel: martial peak
Source: read full novel
Downloaded fully

**Comment by nanihadesuka** [comment]
Fixed with change c68aaa8. The fix will be in the next release. For now you can restart the app as a temporary fix.

**Comment by Kelsinga** [comment]
Great, thanks
