### ISSUE TITLE
[Feature Request] Toggle display android status bar

### ISSUE THREAD

**Issue by Moortu** [nanihadesuka/NovelDokusha#102]
when I'm reading, I do not get any notifications.
So I have to manually first pull up the NovelDokusha menu and then the android status bar so see if I got any messages or even the time.

It would be great if there was a toggle so people can choose to show the status bar of android or not.

The work would be to add a checkbox toggle to the settings, either MoreSettingDialog or SettingsScreenBody
in ReaderActivity.kt line 322 check the setting and based on that show it or not.

**Comment by nanihadesuka** [comment]
Added with a522196baaf576b55dad0c11d0677feaf826c335
Will be available in next version release
