### ISSUE TITLE
Novelupdates doesn't work

### ISSUE THREAD

**Issue by nasif-naseef** [nanihadesuka/NovelDokusha#103]
Its showing no chapter found for novel updates as source.

**Comment by nanihadesuka** [comment]
After some digging I found out you need to login to get the links (since 5 months ago). Will think something up.

**Comment by nanihadesuka** [comment]
Implemented in 605cf6da00e3937074f67ca9096e97fbbe295bc9

**Comment by nanihadesuka** [comment]
You need to log in from web view and login from there. Will make UI more clear for this in the future.
