### ISSUE TITLE
[Feature Request] select chapters below/between

### ISSUE THREAD

**Issue by Moortu** [nanihadesuka/NovelDokusha#105]
When you select a chapter you get options for selecting more chapters, marking as read/unread etc.

Sometimes you want to mark a batch of chapters as read or unread or download them.
Right now there is no way to only select a batch of chapters except by hand.

so requested feature is, after selecting 1 chapter, give an option to select all chapters below.

**Comment by nanihadesuka** [comment]
You can long long click and it will select all the chapter between the last selection and current selected.

But will think of adding the button too.

**Comment by Moortu** [comment]
I thought I tried that... but it works.

User error it seems. A button isn't needed then
