### ISSUE TITLE
[bug] restore database doesn't seem to work

### ISSUE THREAD

**Issue by Moortu** [nanihadesuka/NovelDokusha#106]
I backupped my database, but when I try to restore it on another device, nothing happens.

backup:
https://drive.google.com/file/d/1pEtNxeGVmWGwRfF3vMAID2YBpVnEWf_g/view?usp=drive_link

**Comment by nanihadesuka** [comment]
Phone, OS version, app version, etc please

**Comment by Moortu** [comment]
Backup made on:
Samsung galaxy fold 5
Android 14
Appversion: 2.0.1

Tried restoring on
Onyx Boox Palma, ereader that runs android.
Android 11
Appversion 2.0.1

**Comment by nanihadesuka** [comment]
Only happens in new android version (14 and up). Reason: missing new permission for foreground service backup type.
Fixed in new version
