### ISSUE TITLE
[Source Request] Chinese and English

### ISSUE THREAD

**Issue by OshekharO** [nanihadesuka/NovelDokusha#117]
http://www.4ksw.com/
https://m.xs777.org/
http://m.xiaoshubao.net/

https://novelbuddy.com/
https://lnmtl.com/
https://novelsemperor.com/
https://ranobes.top/
https://wtr-lab.com/en (api)
https://noblemtl.com

Also is it possible to add inbuilt translator like Google translate? So that it can translate chinese novel into English?

**Comment by nanihadesuka** [comment]
@OshekharO the translator feature already exists

**Comment by OshekharO** [comment]
> @OshekharO the translator feature already exists

Where? When I tried reading Indonesian novel I didn't see anywhere?
