### ISSUE TITLE
Cover 

### ISSUE THREAD

**Issue by hamunoz** [nanihadesuka/NovelDokusha#119]
error in the cover in the search, it does not show the sources
Novel Hall
Wuxia World
Novel Bin
![Screenshot_20240627_080954_NovelDokusha](https://github.com/nanihadesuka/NovelDokusha/assets/26285811/60b59c30-483c-4404-8457-38dc9d2a78d5)

**Comment by nanihadesuka** [comment]
Reason:
- Novel Hall: The website doesn't give you the cover when in searcher so I can't show it either. You can instead force reload inside the book chapter list screen and you will get the cover.
- WuxiaWorld: fixed with a1dab1b
- NovelBin: working for me (TM)
