### ISSUE TITLE
User can Login to read locked chapters.

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#12]
Can you add where user can login to read locked chapter.
like webnovellight i locked a chapter and user A has access to that chapter, when he signin we store that cookie and when he visit that chapter because we have the cookie he can read the chapter.

**Comment by nanihadesuka** [comment]
Did you try going to the web page from the webview included in the catalog page? If you click there it will try to grab all the cookies and headers, so if you login it will also grab the login cookies and should be able to work.

**Comment by nanihadesuka** [comment]
The button for the webview is in the catalog page, you must click the "earth" icon .

**Comment by Nabeelshar** [comment]
Thanks~
