### ISSUE TITLE
Novel updates stoped showing search results 

### ISSUE THREAD

**Issue by Mashrafidipto** [nanihadesuka/NovelDokusha#120]
I have logged into novel updates. There are no search results for any novels
Device:Redmi note 11
Android version:13
![Screenshot_2024-06-28-14-25-19-613_my noveldokusha_1](https://github.com/nanihadesuka/NovelDokusha/assets/69859785/aa8539cb-52ed-495c-88cb-860d7164fbe4)

**Comment by nanihadesuka** [comment]
Did you try to login from within the webview or the browser? You must do from the webview. (go to novel updates source -> click open in webview, login)

**Comment by nanihadesuka** [comment]
I know is not very clear how to do it, will improve the UI for these cases in next version

**Comment by Mashrafidipto** [comment]
![Screenshot_2024-06-29-20-33-10-868_my noveldokusha-edit](https://github.com/nanihadesuka/NovelDokusha/assets/69859785/19fcc666-f987-4c15-be48-944479cb6a25)
Logged in from this button.
I can read all the chapters just no search results.
Thanks in advance.

**Comment by nanihadesuka** [comment]
Fixed in 25793aa
