### ISSUE TITLE
Opening Local source crashes to Finder view

### ISSUE THREAD

**Issue by MarkMad** [nanihadesuka/NovelDokusha#130]
I have two local folders added. 
I'm quite sure I was able to get to a list of files before but also crashed when I picked an EPUB file but now it just crashes even before showing a file list. 

It also crashes the app sometimes instead of just going back to the Finder view.

Motorola edge 20 fusion 
Android 12

**Comment by nanihadesuka** [comment]
Unable to reproduce. 

Have you tried removing the folders and adding them again?

If that doesn't work please specify the steps you do with as much details as possible.

**Comment by nanihadesuka** [comment]
Any updates?

**Comment by MarkMad** [comment]
Sorry, I just saw your reply today. The issue may be related to one folder which has several epubs but only one is showing up after I select the folder. By specifying only the folder that was working fine, it worked, and then I added the second folder, which only displays the one EPUB. Maybe the epubs in that folder isn't formatted correctly?
