### ISSUE TITLE
Infinite scroll goes in wrong direction of chapters

### ISSUE THREAD

**Issue by drewbitt** [nanihadesuka/NovelDokusha#132]
May be dependent on chapter names, but infinite scroll will, upon ending a novel chapter, bring up the previous chapter instead of the next, and there's no way of changing that.

Source: NovelBin

**Comment by nanihadesuka** [comment]
Seems the list is being loaded backwards... Will fix it for the next release.

**Comment by nanihadesuka** [comment]
[afb7f71](https://github.com/nanihadesuka/NovelDokusha/commit/afb7f71ecabdf3c2a829fb8f9129823428c9b769)
