### ISSUE TITLE
Increase range for font size option

### ISSUE THREAD

**Issue by egerardoqd** [nanihadesuka/NovelDokusha#133]
I have vision problems, so I have my device with the larger screen size option selected, this increase the font in all my device but the font size in the app is fixed to determined size. Please consider extending the range for the text size option. Maybe 32. Thanks.

**Comment by nanihadesuka** [comment]
In android accessibility for text there are two options:
Font size and display size.
Can you try increasing font size in system settings and see if the text is big enough?

**Comment by egerardoqd** [comment]
The font size helps, but it breaks the UI of several other apps with a comfortable size. I'm ok with the font size for the UI, but it's hard if I have to read for a while.

**Comment by nanihadesuka** [comment]
Increased font size for reader from 24 max to 32 in commit 705cebdadc2812a0d4208fd05d2671e42f01aef7
Will be available in next release
