### ISSUE TITLE
Help Needed: Issue with Chapter Navigation in Novelbin and Similar Extensions

### ISSUE THREAD

**Issue by Seyam7537** [nanihadesuka/NovelDokusha#134]
When using Novelbin extension, or other extentions where Chapter 1 is displayed at the very bottom by default, When you access Chapter 1 and scroll down, it says last chapter. Conversely, when you scroll up, it moves to Chapter 2. This behavior persists even if you change the sorting order.
![Screenshot_20240731_033050_NovelDokusha](https://github.com/user-attachments/assets/be45a297-de3d-43d2-bcbd-f50c1aecb7f5)
![Screenshot_20240731_033110_NovelDokusha](https://github.com/user-attachments/assets/1b7527bd-c23b-4677-9520-304ee3abdb97)

**Comment by nanihadesuka** [comment]
Duplicated https://github.com/nanihadesuka/NovelDokusha/issues/132
Fixed in next version
