### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Enzymeium** [nanihadesuka/NovelDokusha#147]
Requesting for the app to have a feature where you can see where the data or the downloaded chapters are stored in the device

cause I can't find the app directory 🙏

**Comment by nanihadesuka** [comment]
The data is all stored inside the app. No folders. 
Clarification, the app doesn't create folders, it all gets stored in an internal database. No plants to make it "easy" to consume from a folder.

If you really want the downloaded data, you can create a backup of all the novels you downloaded (go to settings -> backup). Inside there will be the sqlite database with all the entries.
