### ISSUE TITLE
Bug: can't drag the cursor down or up

### ISSUE THREAD

**Issue by Seyam7537** [nanihadesuka/NovelDokusha#149]
I can't drag the cursor down or up to copy. I can only copy a block of text. I wanted to copy the whole text 
![Screenshot_20240817_031456_NovelDokusha](https://github.com/user-attachments/assets/31d1a293-0440-4bce-b49a-8bdeb4c74e9d)

**Comment by nanihadesuka** [comment]
Hello @Seyam7537. This is working as expected, given each paragraph is split into its own "text view".
Unfortunately text selection from multiple "text views" is not something supported natively in Android (for now) and any workaround is a convoluted mess. 
Will not try to fix it.

Thanks anyway.
