### ISSUE TITLE
Bug: error 

### ISSUE THREAD

**Issue by Seyam7537** [nanihadesuka/NovelDokusha#150]
![Screenshot_20240817_170337_NovelDokusha](https://github.com/user-attachments/assets/a4898ee5-cca6-48ff-9964-b49447338ed1)

**Comment by nanihadesuka** [comment]
Have you tried reloading?

**Comment by Seyam7537** [comment]
Ya it works when I get out of the chapter and click back in. But sometimes it shows but again.

**Comment by nanihadesuka** [comment]
That means you phone is having connectivity issues, and that makes the loading fail sometimes. Another possible option is that the website is having loading issues. None of those cases can be solved by the app/me. You will have to just keep retrying failed ones until they load.

Hope that helps.
