### ISSUE TITLE
Need vpn like system.

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#17]
when i am trying to add source https://www.mtlnovel.com/ , it's showing 404 or something. need vpn or something.
like this https://github.com/kazemcodes/tachiyomi-extensions-1.x/blob/master/sources/en/mtlnovelcom/main/src/MtlNovel.kt

**Comment by nanihadesuka** [comment]
Means the url you request is invalid
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
