### ISSUE TITLE
The ability to read out the novel

### ISSUE THREAD

**Issue by antaxiom** [nanihadesuka/NovelDokusha#18]
Firstly I'd like to thank your effort on this app, it's very well done for what seems to be a two person effort. 

I understand this is a large request that will probably need a lot of refinement, but in future I'd like a feature where you could have a text to speech reader read out the novel while highlighting what line it is currently on, I am new to reading novels on a phone so this could be of use.  Some other features that could accompany this could be the ability to change the tone voice if the novel has dialogue (indicated by a set of "") and the ability to change the reading pace or set it to change lines as one scrolls (instead of scrolling on its own). 

If needed I could expand on this, but I just wanted to make this "issue" as more of a feature suggestion for when the app is more mature.

**Comment by nanihadesuka** [comment]
Yeah, I also had this same idea. I did a test long ago, worked fine but I want to think how to make the best interface for it, the hardest part in my opinion.

**Comment by nanihadesuka** [comment]
@antaxiom merged to master, I think it has any possible option one would want and the UX I think is intuitive enough.

**Comment by antaxiom** [comment]
Wow, thanks so much for adding this feature even after so much time!
Unfortunately I'm not at my computer right now so I can't build and test it
out.
I'll do it when I'm home.

**Comment by antaxiom** [comment]
I see, I'm no designer, but I could help mock something up and test it if
needed. Unrelated to this I have found a minor bug, the "black" theme also
makes the selection of any buttons black, so if I select various chapters
they are indistinguishable from unselected chapters. This may have to do
with my OLED display and brightness.

**Comment by nanihadesuka** [comment]
I've changed the UI for the chapter list selection mode, now should be easy to tell in black theme.
