### ISSUE TITLE
Paragraph comment! 

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#19]
Can you make a paragraph comment system and store data in firebase.
Like when person hold the paragraph a comment system shows up and a person can comment and reads other people comments!

And all the data can be store in firebase.

PS:- If you decide to make it make it easily so when I run this on Android studio, I can also test it.
Thanks.

**Comment by nanihadesuka** [comment]
Outside the scope of this project, sorry :/.
