### ISSUE TITLE
[Feature Request] Support for adding fonts.

### ISSUE THREAD

**Issue by krypton-kry** [nanihadesuka/NovelDokusha#2]
I believe adding a feature to use custom font files ( say ttf ) instead of using only the default ones available would be a great addition to the app.

A few simple ideas include:
> Manually place required ttf in a specific folder , for example say ```/storage/emulated/0/fonts``` and read from there

> Automatically by using a web view to open Google and then detect ttf downloads and use the downloaded ttf ( like in Moon reader )

P.S. : Absolutely love the app ❤️

**Comment by nanihadesuka** [comment]
The feature would be nice to have indeed but I won't implement it . You can however do pull request and we then can see it is worth it. (also, in my opinion, it would be best to have it on private storage instead of public "emulated/0" folder)
