### ISSUE TITLE
Page Reading instead of Endless Scroll

### ISSUE THREAD

**Issue by Volen-M** [nanihadesuka/NovelDokusha#25]
I was wondering if it would be possible to decide between endless scroll and a page setup for reading.
I've gotten far too use to reading and clicking on volume buttons at this point

**Comment by Nabeelshar** [comment]
There should be a option to swap but endless scroll is amazing feature which is missing from allot of apps

**Comment by nanihadesuka** [comment]
@Volen-M what about just adding the option to scroll down/up one full page with the buttons, would achieve the same effect.

**Comment by nanihadesuka** [comment]
Discarded, will add however a scroll up down button in the future
