### ISSUE TITLE
Selectable text (reader)

### ISSUE THREAD

**Issue by Volen-M** [nanihadesuka/NovelDokusha#27]
Is it possible to change the font settings to a double tap instead of hold to permit for selectable text?
A lot of webnovels have links to images for explanations, and selecting text allows users to use Android's build-in Google Assistant search for words we aren't sure of. (I'll be damned if I ever remember all the names of the Chinese beasts and weapons)

**Expected Behaviour 1:**
Holding onto a word with finger in the reader selects text.
**Current Behaviour 1:**
Holding onto a word with finger in the reader shows font settings

**Expected Behaviour 2:**
Double-tapping screen shows font settings
**Current Behaviour 2:**
Double-tapping screen does not do anything.

Thank you very much for all you do.

**Comment by nanihadesuka** [comment]
Added in 387e4b769f19e26882e511c0f86d1fc017139f0c
