### ISSUE TITLE
Please fix versioning

### ISSUE THREAD

**Issue by IzzySoft** [nanihadesuka/NovelDokusha#3]
The APK at release 1.2.0 identifies with `versionName: "1.0"` (which should be "1.2.0") and `versionCode: 1` (which, as this is the 3rd release, should be 3 or higher). Can you please fix that? `versionCode` is used by Android to tell versions apart, so 1.2.0 would not be considered an update to any of the previous versions. And `versionName` certainly helps when users report issues :wink:

While on it: Maybe you could include some screenshots with the Readme?

**Comment by nanihadesuka** [comment]
Done

**Comment by IzzySoft** [comment]
Thanks a lot! That enables me to promote your app via my repo. It will [become available there](https://apt.izzysoft.de/fdroid/index/apk/my.noveldokusha) within about 2.5h from now, and people can use the [F-Droid](https://f-droid.org/) client to install it and be notified about updates (within 24h of your creating a new release and attaching the APK to it). If you wish, you're welcome to use [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from the Readme.
