### ISSUE TITLE
Favorite your Source.

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#30]
Favorite your source and it appears in the bottom menu between library and finder
**with the exception**
You can favorite only one source

**Comment by nanihadesuka** [comment]
Instead of favourite, pinned sources would be better (like in tachiyomi)

**Comment by Nabeelshar** [comment]
Yeah thats good for pinned, on the finder page but i wanna add/see/find NU in the menu because menu has not alot of items

**Comment by nanihadesuka** [comment]
Add with bdf348045299ff8dc3e4251978c9489d5356c43a, you can pin multiple.
