### ISSUE TITLE
Megre Novelupdates db source NU source.

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#31]
Can you merge db NU and Source Nu because then there is no need for db(as baka is not working) optional(. and added that to menu)

It will look something like this 
![ ](https://github.com/Nabeelshar/NovelDokusha/blob/master/screenshots/nu1.png?raw=true)
![ ](https://github.com/Nabeelshar/NovelDokusha/blob/master/screenshots/nu2.png?raw=true)
![ ](https://github.com/Nabeelshar/NovelDokusha/blob/master/screenshots/nulast.png?raw=true)

**Comment by nanihadesuka** [comment]
Both baka and novel updates work, double check please :/

**Comment by Nabeelshar** [comment]
[Image](https://ibb.co/5nNW9Wn)

Baka update is not working, also Novelupdates is working I just wanna combined Novelupdates from database with novelupdates from sources/scraper.

**Comment by nanihadesuka** [comment]
This error looks more like a problem with your mobile connection, something is probably trying to create an unsecured connection and thus this error.

Have a look at this: https://github.com/koush/ion/issues/825
https://stackoverflow.com/questions/68846752/javax-net-ssl-sslexception-unable-to-parse-tls-packet-header-in-urlconnection-c

Don't know what to say, have no way to reproduce so ...
