### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#33]
How can I change the package name because sometimes I test this on my mobile and it destroy my old data.
So I wanna change the package name so it can't conflict with my main app which I use for personal reading.

**Comment by nanihadesuka** [comment]
Sorry but this is not stackoverflow.

**Comment by nanihadesuka** [comment]
https://letmegooglethat.com/?q=stackoverflow+andorid+change+app+package+name

**Comment by Nabeelshar** [comment]
Lmao, I know how to change the app name.
but it's break your the app.
_will probably post the error here sometime later_
