### ISSUE TITLE
Show content (chapter list)

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#34]
Show Content (chapter list) page on chapters page..

**Comment by nanihadesuka** [comment]
This is already done, what do you mean otherwise, the reader?

**Comment by AhmadNaruto** [comment]
isn't that already there.?! maybe it's just the design that matters

**Comment by Nabeelshar** [comment]
> isn't that already there.?! maybe it's just the design that matters

Where it is? Send screenshot

**Comment by nanihadesuka** [comment]
Ok, so the idea would be to add the chapters list on the reader page too? Yeah it would be easy to do, but I don't see what benefits will bring compared to what there is now, currently you can just go back instantly to the chapters page and do the same thing with the same number of clicks/gestures, also would duplicate functionality which I'm not fond of from a visual & utility point of view.
So, if there is not clear positive reason for it, I'm against it, but, if you can convince me then 👯

**Comment by AhmadNaruto** [comment]
> Ok, so the idea would be to add the chapters list on the reader page too? Yeah it would be easy to do, but I don't see what benefits will bring compared to what there is now, currently you can just go back instantly to the chapters page and do the same thing with the same number of clicks/gestures, also would duplicate functionality which I'm not fond of from a visual & utility point of view. So, if there is not clear positive reason for it, I'm against it, but, if you can convince me then 👯

aah.. I think I understand. there may be times when we need it. to jump to a specific chapter without needing to return to the main page.

**Comment by Nabeelshar** [comment]
> So, if there is not clear positive reason for it, I'm against it, but, if you can convince me then 👯 


Okay let's say you have read a novel before but you don't remember which was the last chapter so you open the app you open a chapter let's say 25 when you open the chapter that you have read so you go back then click again to 28 chapter but this is not the chapter that you read so you again go back this looped. So this is kinda annoying.

There are more cases like you wanna see what chapter you are reading until the last chapter or you wanna check what's the last chapter number, while on chapter (not going back)

**Comment by nanihadesuka** [comment]
Knowing last read chapter can be displayed easy in the chapters page by having the last chapter read with different colour.
The what chapter are you on and how many till the end can be seen from the top info on the reader page.
That last use case of seeing chapters while on the reader makes sense, but I'm not sure how useful is that, usually when you read a novel you read it and when you search for chapters to search for chapters, the interaction between the two is rare, one use case wold be if you are in a "speech mode" but still I don't see the need. 

Note that I'm not trying to turn your ideas down, I'm just looking at what I would consider my ideal reader and to try to avoid the less possible clutter for the reading experience.

**Comment by nanihadesuka** [comment]
Idea wont be implemented. You can already see the chapters on the chapters page and there is no need to duplicate information.
