### ISSUE TITLE
Change dark and light mode while reading/on reading page

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#35]

**Comment by nanihadesuka** [comment]
Yes I was planning on adding that sooner or later but I'm thinking on the best UI for all the settings while keeping the reading experience 100% perfect, I don't want an ugly mess. Sometimes less is better :D

**Comment by nanihadesuka** [comment]
Added with 9476c1b18c1c0c162427ff32969796e01083c59c
