### ISSUE TITLE
Doesn't remember previous state 

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#38]
So I left the chapters (in middle) and  left app when I reopen it's in top/start of app, it doesn't remember where I left the app.

**Comment by nanihadesuka** [comment]
Followed steps, still can't reproduce. I also tried it while I have "don't keep activities" developers option enabled but still works fine. The app is designed to save the position at chapter completition, onResume, onStop and every 10 seconds so it should work. Maybe is something device specific. If you want to look at the source for the specific function look at `ActivityViewModel.kt` and friends.

**Comment by Nabeelshar** [comment]
Okay I will look into it maybe it's my mobile problem.
Also it only apps in mtlnovels doesn't happens anywhere else.

**Comment by nanihadesuka** [comment]
If you can no longer reproduce the problem, close this issue please. @Nabeelshar

**Comment by Nabeelshar** [comment]
maybe its because of debug mod.
