### ISSUE TITLE
Sources request

### ISSUE THREAD

**Issue by MrChuw** [nanihadesuka/NovelDokusha#4]
https://reaperscans.com.br / https://saikaiscan.com.br / https://neoxscans.net / https://arthurscan.xyz / https://silencescan.com.br

Some Brazilian sources that I can remember

**Comment by nanihadesuka** [comment]
Sorry, but for the moment the app is English only.  Maybe, later on, I will add support for multiple languages but no plans.
Anyway, thanks for the suggestion MrChuw.

**Comment by nanihadesuka** [comment]
@MrChuw  for the moment I added one brazilian source, Saikai in the version 1.3.0. You can enable it (default only english) in the finder app bar  languages action button.
