### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#42]
Need reload/retry button on chapter reading place.(error like internet connection problem)
Because if there is error I need to revisit the page/chapter. 
![IMG_20220512_201241.jpg](https://user-images.githubusercontent.com/96086329/168108571-0d3ce5ba-5b2f-4279-b821-c7215f3f319d.jpg)

**Comment by AhmadNaruto** [comment]
maybe can add dna cache or better if DoH implemented.

**Comment by nanihadesuka** [comment]
And what would that accomplish for this error?

**Comment by nanihadesuka** [comment]
352b240a9847d921f33883289f777dc168f8b959
