### ISSUE TITLE
Scrolling chapters lags

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#44]
Scrolling through chapter is laging
https://user-images.githubusercontent.com/96086329/168474302-54df4758-b863-4a72-bab8-fef54b02978a.mp4

**Comment by nanihadesuka** [comment]
Yes, I know. I did look at it but can't find the reason for the lag. Don't forget that compose UI performance is much worse in debug build, use release builds to test real performance.
