### ISSUE TITLE
Library tab: bottom sheet options, sort by Last read.

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#45]
Okay so I don't which is last read sign ⬇️ or ↕️ but whatever I click it doesn't show last novel that I read.

`I can show you videoshot if you want`

**Comment by nanihadesuka** [comment]
It doesn't sort by last read but by "read" or "not read".
If you want by last read we can add it.

**Comment by Nabeelshar** [comment]
Oh, lol I thought it last read because ⬇️ means last in some places.

That would be amazing!

**Comment by nanihadesuka** [comment]
Added 2ae010750e115c899a826b614cc50cd1fea2e896
