### ISSUE TITLE
Novel translation option

### ISSUE THREAD

**Issue by RickyM7** [nanihadesuka/NovelDokusha#5]
It would be awesome if you added an option to translate the novels using a service like google translate or something similar.

**Comment by nanihadesuka** [comment]
I will see what can be done but can't promise anything.

**Comment by RickyM7** [comment]
> I will see what can be done but can't promise anything.

Thank you very much!

**Comment by Nabeelshar** [comment]
If this is added we can just add raw novels sources and it will auto translated.

**Comment by RickyM7** [comment]
> If this is added we can just add raw novels sources and it will auto translated.

Raw and English sources because Google Translator and other translators can do a better translation from English to any other language.

**Comment by Dlordload** [comment]
hope this helps https://github.com/vitalets/google-translate-api

**Comment by nanihadesuka** [comment]
@RickyM7 @Dlordload feature added to the last release. 
https://github.com/nanihadesuka/NovelDokusha/releases/tag/v1.7.0
