### ISSUE TITLE
v1.7.0: size increase by factor 10 and a bunch of non-free components added

### ISSUE THREAD

**Issue by IzzySoft** [nanihadesuka/NovelDokusha#53]
No idea if this was intentional, but the APK size jumped from about 4M to over 50M with v1.7.0. Further, the app is no longer FOSS as a couple of non-free components have been added:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* ML Kit (/com/google/mlkit): NonFreeDep,Tracking

4 offenders.
```

My guess is you added Google's ML Kit, which dragged in the other dependencies.

If this was intentional: Will you offer a FOSS flavor (and APK) without those? If it was not intended: Will you revert that? Thanks in advance!

**Comment by nanihadesuka** [comment]
For the app size I just noticed to, seems I added the dependency that has the English model already bundled and is quite heavy.
As for the dependency on google, I'm willing to go the extra mile if there is an equivalent FOSS toolkit with the same capabilities (download models and translate on-local), do you know of some? Otherwise, I could look to make a translation-less flavour, but is quite a loss of functionality. Does F-droid explicitly forbids apps with google dependencies? I know this one (MKKit) will send some statistic of the API usage.

**Comment by nanihadesuka** [comment]
Yes, the size change is because the apk includes the necessary shared native libraries for each cpu arch.

**Comment by IzzySoft** [comment]
I'm no Android dev myself, so I'm not really aware of MLKit's full capabilities and what FOSS alternatives to it exist. I know some use it for QR code stuff, and there are plenty libs for it. But I've no ideas of models etc.

> Does F-droid explicitly forbids apps with google dependencies?

Yupp – non-free libraries (or build dependencies) are a no-go with F-Droid. [Your app is currently in my repository](https://apt.izzysoft.de/fdroid/index/apk/my.noveldokusha), which has less strict rules – but I had to reject today's update based on above issues (with my repo, size limit per app is at 30M, and non-free deps are only tolerated to a degree; with 4 of them you're already hitting the hard border). The trouble with those is you can never be sure what they really do "behind your back", as they are a black-box. And they taint your app which, with them included, can no longer be called "free/libre", as the "libre" part is gone.

> size change is because the apk includes the necessary shared native libraries for each cpu arch.

Ah, that could then be worked-around by having single-arch APKs (I usually pick the armeabi-v7a one then as that's still supported by the most devices).

**Comment by nanihadesuka** [comment]
Ok, I understand. I can't see to find any FOSS translation alternatives that meet my needs so I will create a flavour without the google dependencies for the next release (date unknown). For now you can just not upload the current new version. As for the size, will also make multiple apk to target each arch for the next release, then hopefully will be less than 30 mb.

**Comment by IzzySoft** [comment]
Thanks a lot, @nanihadesuka! Can you please send me a ping here when I shall check again? Currently, auto-update is disabled for your app in my repo. Once the new release (with the APKs attached) is there, I can check and adjust accordingly.

**Comment by nanihadesuka** [comment]
@IzzySoft can you pass me to tool you use to check for non foss dependencies? I've already made the changes, now there are two flavours: "foss" and "full". But would be nice I can make sure myself is really that way. Is a CLI APK analyser tool right?

**Comment by IzzySoft** [comment]
Yes, it's a FOSS tool and using CLI. Instead of simply pointing you to the source, let me point you to its how-to: [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2). Everything you need is linked from there. And disclosure: article as well as the CLI wrapper and the list of library definitions are authored by me. Oh, and those two `.txt` files now properly carry the `.jsonl` file extension :wink:

**Comment by nanihadesuka** [comment]
@IzzySoft new release. Now exist a flavour "full" and another "foss". Foss flavour will not contain any google, tracking, etc. Also there is no need to split by arch as the foss apk size is 5MB.

**Comment by IzzySoft** [comment]
@nanihadesuka thanks! The new foss build looks fine :smiley: I've just re-enabled auto-updates and added the new version.
