### ISSUE TITLE
Automatic translations of contextual text (title, description, chapters list name) 

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#55]
Can you make Translation work for whole source sources instead of chapters.

**Comment by nanihadesuka** [comment]
Meaning?

**Comment by Nabeelshar** [comment]
Like when I open a source example wuxiaworld I wanna translate the title and description.

**Comment by nanihadesuka** [comment]
Will think about it, but for the moment the translation will only happen inside the reader and only for the chapters text. I need to consider all the code design decisions and UX.

**Comment by nanihadesuka** [comment]
I decided that is best to only translate the reader content, this feature would be bring too much complexity for little benefit and the interface UX would become too complicated.
