### ISSUE TITLE
[Source Request] Korean Novels MTL

### ISSUE THREAD

**Issue by RickyM7** [nanihadesuka/NovelDokusha#58]
If possible, please add this source to the app. Thank You!

Description: Korean Novels and Webnovels Machine Translation.
Language: English
Link: https://www.koreanmtl.online/?m=1

**Comment by nanihadesuka** [comment]
Added in commit 0701092acd3509bda69b5fb1820490c16271a921
Will be available for the next release (undefined date)

**Comment by RickyM7** [comment]
> Added in commit [0701092](https://github.com/nanihadesuka/NovelDokusha/commit/0701092acd3509bda69b5fb1820490c16271a921) Will be available for the next release (undefined date)

Thank you very much!
