### ISSUE TITLE
e: ***\NovelDokusha-1.4.0\app\src\main\java\my\noveldokusha\uiAdapters\ProgressBarAdapter.kt: (5, 24): Unresolved reference: databinding

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#6]
getting error when trying to run the app in android studio emulator .
Full error
https://pastebin.com/haKkXJjJ

**Comment by nanihadesuka** [comment]
That error means there is something wrong with your android studio or gradle configuration. Those errors tell you the viewBinding gradle plugin isn't generating the XML view holders automatically ( e.g. reader_activity.xml should have generated an ActivityReaderBinding).

**Comment by Nabeelshar** [comment]
Okay will check that, but I haven't changed anything in the android setting flutter apps are running fine.
Another issue is that it looking for signin certificate. 
You can try to download this source code and run it on Android studio.
Maybe it giving errors to new project

**Comment by nanihadesuka** [comment]
You can delete the signing certificate need by removing the code from the build.gradle file. I should probably fix it so it works without the keys thought.

**Comment by Nabeelshar** [comment]
i double check, and found issue, i think its problem with database.
do you have discord?

**Comment by nanihadesuka** [comment]
No, I don't have discord :(
Ok, tried. Download from github, changed `isSignBuild`  to `false` in `app/build.gradle.kts"  and got an hilt plugin error. Then I  fix it with https://www.youtube.com/watch?v=CoQ7ikBPgR8.  Apart from that I didn't get any error and compiled just fine.

**Comment by nanihadesuka** [comment]
Did you check ProgressBarAdapter exists and wasn't deleted by accident?

**Comment by Nabeelshar** [comment]
Thanks~ so problem was that i was commenting out whole ```isSiginBuild``` and lol i also watch that video and fixed hilt plugin.
also i am trying to add this website https://webnovellight.com/ (its mine but i am getting error 

after description
on fetching chapters
```
unkown error 
info;no info
 
Message
HTTP error fetching URL, status=404, URL=[https://webnovellight.com/wp-admin/admin-ajax.php]```

**Comment by nanihadesuka** [comment]
https://webnovellight.com/wp-admin/admin-ajax.php also returns 404 in the browser.
I set as fixed this issue.
For the website you can do new issue or PR or whatever you want :D
