### ISSUE TITLE
Request source: https://toc.qidianunderground.org

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#63]
Request source https://toc.qidianunderground.org

Reasons:- it doesn't have copyright text from pirate sites like read at wuxiaworld etc and is updated chapters.

**Comment by nanihadesuka** [comment]
The way the chapters are displayed in the webpage looks like a pain to manage but will see.

**Comment by Nabeelshar** [comment]
There  are resources which have already added this like readerorg with jsoup

**Comment by nanihadesuka** [comment]
Webpage no longer exists/working. Won't add.
