### ISSUE TITLE
Need more repositories

### ISSUE THREAD

**Issue by AtreussOT** [nanihadesuka/NovelDokusha#69]
Sería genial si tuvieran mas repositorios para buscar novelas, como los que estan en lnreader o tener la opcion desde la app de agregar repositorios nuevos.

**Comment by nanihadesuka** [comment]
Por motivos de mantenimiento y tiempo sólo añadiré nuevos repositorios (sources) si no puedes encontrar las novelas que quieres en los repositorios que hay ahora.
Si quieres recomendar añadir mas repositorios, crea un nuevo ticket, di que novela no encuentras, lenguaje y que pagina web la tiene.
