### ISSUE TITLE
Please add library/folder scanning

### ISSUE THREAD

**Issue by d4f5409d** [nanihadesuka/NovelDokusha#72]
It would mean a lot to me that I can read my favorite downloaded books with a modern epub reader UI. However it would be the most convenient to me to scan the whole folder dedicated to it. Thank you :)

**Comment by nanihadesuka** [comment]
Will have to think about it, the app has EPUB import features but is mostly focused for online novels

**Comment by d4f5409d** [comment]
Thank you ❤️
