### ISSUE TITLE
UI elements and text leaves trails on reader screen

### ISSUE THREAD

**Issue by flgsercan** [nanihadesuka/NovelDokusha#75]
Device: Huawei Y6s
Android: 9
App Version: v1.9.0

In reader screen, every moving thing leaves a trail which blends together and makes reading impossible after a while. ![Screenshot_20230228_021151_my.noveldokusha.jpg](https://user-images.githubusercontent.com/32499577/221711212-05fa5af7-7fa4-46bb-9575-7a7454bd291c.jpg)

**Comment by flgsercan** [comment]
After trying some stuff I found that it is related to themes. Dark and grey work fine while black and light cause this bug.

**Comment by nanihadesuka** [comment]
@flgsercan Thanks for this weird bug, fixed in 517e275279c901e557df63ae1bc2bc84542d75b8 and will be included in next release
