### ISSUE TITLE
"play" button 

### ISSUE THREAD

**Issue by kenshimoto** [nanihadesuka/NovelDokusha#79]
Would it be possible to add another "play" button on top, next to the other icons underneath the novel title (see screenshot) or something like that? I HATE clicking on the early chapters by mistake and having to "manually" find the exact point I left at. I know it's a problem of mine and not an actual issue, but I would love it and would be very thankful.

![Screenshot_20230325_180129_NovelDokusha](https://user-images.githubusercontent.com/128923772/227732576-738e8609-e610-4f56-a81f-3b23a03a289b.jpg)

**Comment by nanihadesuka** [comment]
Will be part of this PR
