### ISSUE TITLE
source add info

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#8]
Hy,
 I am trying to add this source https://webnovellight.com/
how can i do that,
its showing error on chapter list part.

**Comment by nanihadesuka** [comment]
Send PR or something so I can see the code, you can look at the other ones to see how I do it (I guess you already did that)

**Comment by Nabeelshar** [comment]
lol so i don't know what pr is but here is the code 
here is my last try and 
https://pastebin.com/BK5ZLSbT
here is 
me just changing website
https://pastebin.com/9EAvYLss

**Comment by nanihadesuka** [comment]
PR: Pull request
See github help for more info

**Comment by Nabeelshar** [comment]
so i should pull a request

**Comment by nanihadesuka** [comment]
If you want to add that source to this repository yes. If it works I accept the pull request.

**Comment by Nabeelshar** [comment]
that source isn't working its showing error on chapterlist.

**Comment by nanihadesuka** [comment]
d46e35457ad51a40ac1dc90a06dfddde3eaa10f3
