### ISSUE TITLE
Export/Import feature not working

### ISSUE THREAD

**Issue by KDJ1863** [nanihadesuka/NovelDokusha#82]
When clicking on button nothing happens. Thank you for your work!

**Comment by nanihadesuka** [comment]
@KDJ1863  Check your permissions for the app, is most likely you denied permission to storage access.

**Comment by nanihadesuka** [comment]
Added a dialog for when a permissions is denied, so the user will be able to go to the app system settings and allow it again.

**Comment by KDJ1863** [comment]
> @bradmurray installed last version 2.0.0 ?
> 
> This is indeed weird. I tested it a couple of times already and the export/import don't give me any issues. I didn't mention it before but, the export/import doesn't really need storage permissions as it uses the external explorer to access the files. I just added the permissions check in case of older android version that doesn't have the features. 
> 
> Haven't tried with grapheneOS and as you said it shouldn't not matter. 
> 
> Will reopen and check it again

Unfortunately, it's still not working for me. My phone(Samsung S23U) doesn't allow me to give allow an app a permission unless the app asks me to grant it. So I can't give the app access to storage. Thank you for your work.

**Comment by nanihadesuka** [comment]
@bradmurray @KDJ1863 finally found the reason 349c7f726c7506025607870c4f23f5b6956f3839, new version with fix at https://github.com/nanihadesuka/NovelDokusha/releases/tag/v2.0.1

**Comment by nanihadesuka** [comment]
Test it please and close this issue if it solves the problem

**Comment by KDJ1863** [comment]
> Test it please and close this issue if it solves the problem

It works. Thank you!
