### ISSUE TITLE
Some sources have stopped working

### ISSUE THREAD

**Issue by Mashrafidipto** [nanihadesuka/NovelDokusha#93]
Light novel translations, 1stkissnovel,wuxia sources have stopped working and it's hard to use this app.
Thanks for your work. 
![ResizedImage_2023-08-28_12-41-20_2195](https://github.com/nanihadesuka/NovelDokusha/assets/69859785/78627b88-3b44-4e4a-a64e-3b49d45a4a16)
![Screenshot_2023-08-28-12-38-07-652_my noveldokusha](https://github.com/nanihadesuka/NovelDokusha/assets/69859785/f6e80060-7215-449f-bd13-272fe346fea1)

**Comment by nanihadesuka** [comment]
Yep, some sources changes the HTML and domain name. Next version will have most of them fixed.

**Comment by nanihadesuka** [comment]
wuxia.blog not working the website itself, the rest are now fixed
