### ISSUE TITLE
[Feature Request] Convert any webpage into a book

### ISSUE THREAD

**Issue by wasu-code** [nanihadesuka/NovelDokusha#99]
### Why?
It would let users read from sources not yet added to the app.

### How?
Paste URL in search bar and search for it to create single-chapter book  
or  
Use local directory to store txt files with list of URLs - every file representing a book and every link representing a chapter. Then add them to your library just like local EPUBs.

**Comment by nanihadesuka** [comment]
Not planned, scope of the feature is outside of the app purpose (reading webnovels). As a alternative I can recommend you to create an epub and then use that to import it to the app.
